{% set name = "sox" %}
{% set version = "14.4.2" %}
{% set commit = "b9dd1a86e71bbd62221904e3e59dfaa9e5e72046" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/dmkrepo/libsox/archive/{{ commit }}.tar.gz
  sha256: cb8159178c26adebf177c29fad78563cf8f4f85593030a2e89257bb19a05a2dc
  patches:
    - cmake.patch

build:
  number: 1015
  detect_binary_files_with_prefix: true
  entry_points:
    - play = soxpy.play:main
    - rec = soxpy.rec:main
    - soxi = soxpy.soxi:main
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/sox/
    - {{ pin_subpackage(name, max_pin='x.x.x') }}
    - soxpy

requirements:
  build:
    - cmake
    - ninja
    - make  # [not win]
    - pkg-config
    - {{ compiler('c') }}
  host:
    - libpng
    - zlib
    - xz
    - libsndfile
    - libvorbis
    - libflac
    - libopus
    - speex  # [linux]
    - lame  # [not win]
    - mad  # [not win]
    - python

  run:
    - libpng
    - zlib
    - xz
    - lame  # [not win]
    - mad  # [not win]
    - python


test:
  commands:
    - test -e $PREFIX/include/sox.h      # [unix]
    - test -e $PREFIX/lib/libsox_static.a       # [unix]
    - test -e $PREFIX/lib/libsox.so      # [linux]
    - test -e $PREFIX/lib/libsox.dylib   # [osx]
    - otool -L $PREFIX/lib/libsox.dylib  # [osx]
    - sox --help |grep "FILE FORMATS"  # [win]
    - sox --help |grep "FILE FORMATS" | grep mp3  # [not win]
    - sox --help |grep "FILE FORMATS" | grep flac
    - soxi --help |grep "FILE FORMATS"
    - play --help |grep "FILE FORMATS"
    - rec --help |grep "FILE FORMATS"

about:
  home: http://sox.sourceforge.net/
  license: GPL-2.0-only
  summary: A cross-platform command line utility that can convert various formats of computer audio files in to other formats.
  license_file: COPYING

extra:
  recipe-maintainers:
    - 183amir
    - alexbw
    - sdvillal
