travis:
  secure:
    BINSTAR_TOKEN: R/mE/rNd1/JkutQCUPS9ze6FceHVYKahKFrUlx67pXxCTFdQ1UuZGuZmHnDFxu+p8GpoaYOmm5uxMgnya5Q9yvPYaDrluG4IiODAJUgZ0GpzEIHkewuWFFFCALBuhyxduP7EB8LD6z2crG2Xytu0dmoNyvTKKg6sYAiktW2tDmAveA6Gz/+xHWcmVGKdx7tIVuC4UN9AMYJvkAVhp1P2CdSdI6xvMd7OvNtSAFrv/4iFcU6h849mBWjlArFnWTRow/SbSGnMacjctYSqULqqhJ4vi7emn15fZ0yYA9/Ya0bNzMPOEJCQ6RHiSr/eYxJ45Y9/pPPA3SYBqljSZzLHTmvczoRHRB4Yc91AexD6AP4qr63/OAyvyHntrSdgUn4dcZeKTRC012mtpQ69ZKry/gq7dtyuhaLEe7DYndvCDk4HmnVEhw5nJsANVzlsBp0MBugjyYPGgB2snYgx2L5w0M3SG/NilPt1Hqbb3+wdokouCRRCQIan6+nbPAzp5w68gyY0NGDeX1yTB7YYayxYEZZdNs/IYHRSGgJ/8GZl0h2/9BIIN665O3HY5ZVvq8jbJuqo2vq5Dyk7cSlNIjB8Cam/l62rsk0pMvk/diJUMajfwOttJPEAnrms0Y6WJqwDdM5xoff9zwVjzW1a4rV06I/ksKA1m1oKSepQnOL2vuY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
