appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xWcYruCurYX3W2qb8c2h4Kaww0Z4WdELLDxjPTa2Y6D8bUmprluYtBzxEwDrptOfP7lCSYtvY/AiOlmMXQ69qMeATjSflxIF9H9rZp6+dUdxxMI//+HyGJgsMc4hZIoG7b7jrP7TO/cboSquiiLQWL4inT9lRinVLOUz911gfYb1ucd1M1xyKqqFegTtpVMBHtiqO3WHx5Y4jdhOqxg5tgHcGz5kWI7NE2OibBc0eTcransWdqREH6+T+U6Miislcgp44LFUdxuf3Qx5qUREadRogvJLNm0motPLWm3s8ck2i0exrvGZRvsUiKngAiGzOZGnwpP7oYf6qYT0828cQZhihEom60xrOGt40dXwKkN79vtvQMY6iu/YcF3CzQcqTm6XeV02eiRnYIzVG+RBTyYLzBQstqNQcButmE7ZP+45NSnD9X8sx9WgWhfgyiMfsIg/xl/IcMuCM/9DkX0bf2EvqIQP2tqkqk5Au3PKQ3i+u35ZhXXe7tgt5ST4UVgTrjlmhfFfUFbtbV688pLhTjxvCs5rIImdLJ0Vua070SFtmezA4Tr2YhicaRtAZrDE1xo19pNgceQySsU7MfsDZlqjou8qu63loOw0OsPnSIJP+i2cEJSK9DzHTEq8A2DQdWRUmx96W8kUO9WPd610QUwA0V78rvcpwA1i9wjoSM0=}
conda_forge_output_validation: true
